/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_worldunion_dylanapp_test_JniDemo */

#ifndef _Included_com_worldunion_dylanapp_test_JniDemo
#define _Included_com_worldunion_dylanapp_test_JniDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_worldunion_dylanapp_test_JniDemo
 * Method:    getHelloWordTest
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_worldunion_dylanapp_test_JniDemo_getHelloWordTest
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
